# Generated by Django 5.2 on 2025-04-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
