# Generated by Django 5.2 on 2025-05-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_alter_anuncio_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('fecha_inicio',)},
        ),
    ]
