# Generated by Django 5.2 on 2025-05-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0003_alter_anuncio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
