# Generated by Django 5.2 on 2025-05-12 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0004_anuncio_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
